import Head from "next/head";
import Image from "next/image";
import * as R from "ramda";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps, InferGetServerSidePropsType } from "next";
import IndicatorCard from "@/components/Cards/IndicatorCard";
import { Container } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  indicators,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Test Kabeli Indicadores</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container>
          {indicators.map((item: any) => (
            <IndicatorCard item={item} key={item.codigo} />
          ))}

          {/* {JSON.stringify(indicators)} */}
        </Container>
      </main>
    </>
  );
}

export const getServerSideProps: GetStaticProps = async (context) => {
  const res = await fetch(
    `https://kabeli-api-production.up.railway.app/api/indicators/all`,
  );
  const data: any[] = await res.json();

  const indicators = R.compose(
    R.values,
    R.map((item: any) => item),
  )(data).splice(3);

  return {
    props: {
      indicators,
    },
  };
};
